# quantum_report.py
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted
from reportlab.lib.styles import getSampleStyleSheet
import os

def generate_report(url, risk, message, findings, fixes, kyber_code, dilithium_code):
    os.makedirs("reports", exist_ok=True)
    filename = url.replace("https://", "").replace("http://", "").replace("/", "_")
    pdf_path = f"reports/QuantumShield_{filename}.pdf"
    
    doc = SimpleDocTemplate(pdf_path, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    
    story.append(Paragraph("QuantumShield Report", styles['Title']))
    story.append(Spacer(1, 20))
    story.append(Paragraph(f"Target: {url}", styles['Normal']))
    story.append(Paragraph(f"Risk Level: {risk}", styles['Normal']))
    story.append(Paragraph(message, styles['Normal']))
    story.append(Spacer(1, 20))
    
    story.append(Paragraph("Component Analysis:", styles['Heading2']))
    for f in findings:
        story.append(Paragraph(f"• {f}", styles['Normal']))
    
    story.append(Spacer(1, 20))
    story.append(Paragraph("Recommended Fixes:", styles['Heading2']))
    for f in fixes:
        story.append(Paragraph(f"• {f}", styles['Normal']))
    
    story.append(Spacer(1, 20))
    story.append(Paragraph("Sample Kyber Code (Key Exchange):", styles['Heading2']))
    story.append(Preformatted(kyber_code, styles['Code']))
    
    story.append(Spacer(1, 20))
    story.append(Paragraph("Sample Dilithium Code (Signature):", styles['Heading2']))
    story.append(Preformatted(dilithium_code, styles['Code']))
    
    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by QuantumShield — Prepare for the quantum era", styles['Italic']))
    
    doc.build(story)
    return pdf_path
